#!/usr/bin/env bash
# tests/run.sh — everything, in one command, with nothing installed.
#
# No framework, no dependencies, no build step: node's own test runner and Python's unittest, both
# already on any machine that can build this project. That is the same rule the extensions follow —
# a test suite that needs `npm install` would be the first dependency in a repository whose pitch is
# that it has none.
#
# What is covered, and what is not, stated plainly because a coverage claim nobody can check is
# worth as much as a hash nobody can reproduce:
#
#   covered — pure logic that has actually broken: the Deluge comment/string scanner, which CSRF
#     cookie belongs to which family, how staleness is derived per area, how a tag is read out of an
#     Atom feed, how a version is scraped from a page we do not control, and the three checkers.
#
#   not covered — anything that needs a DOM, a browser, a file handle or Zoho. The panels are
#     browser scripts and are not restructured to be importable: doing that refactor *in order to*
#     add tests would spend the risk before earning the cover. Helpers are lifted out and run alone
#     (see slice.mjs), which proves the logic and not the wiring. A correct function called from the
#     wrong place still passes here.
set -euo pipefail
PYOUT=$(mktemp)
NODEOUT=$(mktemp)
trap 'rm -f "$PYOUT" "$NODEOUT"' EXIT
# **What runs, exactly - not a floor under it.** These were `-ge` bounds, and a bound with slack in
# it stops measuring the thing it is named for: 939 node cases ran against a floor of 922 and 402
# python against 395, so seventeen and seven could have stopped running with the battery still green.
# The comment above them already said «a rise is a line to change in the same commit as the cases
# that caused it», and nothing made that true.
#
# Exact, in both directions, for the reason every ledger in this repository is: a fall is cases that
# stopped running, a rise is cases somebody added and the number is the place they record it. The
# failure says which of the two happened, because they are not the same news.
NODE_EXPECTED=1079
PY_EXPECTED=408
cd "$(dirname "$0")/.."

# The machine that runs this is not the machine the extensions are loaded on: Chrome there reads
# `apps/<app>/` out of a synced folder. That copy used to depend on somebody remembering to ask for
# it, which is a rule, and rules that live only as prose get broken - so it happens here instead.
#
# **First, not last**, and deliberately: a red suite is exactly when you want to look at the thing in
# a browser, and `set -e` would never reach the end of this file. It is a no-op wherever that folder
# is not mounted, and it may never fail the battery - a cloud drive that is offline is not a defect
# in this repository.
echo "── to the test folder ──"
if out=$(bash tools/totest.sh --auto 2>&1) && [ -n "$out" ]; then
  echo "$out" | sed 's/^/  /'
else
  echo "  not mirrored${out:+ - $out}"
fi

echo
echo "── unit: node ──"
# The floor is stated rather than discovered. On node 19 the TAP reporter dies on a multi-byte
# character split across a socket read and `tools/probe.py` stops with it - which reads as a defect
# in the product and is a defect in the environment. Said here, once, at the moment it matters.
node -e 'const m=+process.versions.node.split(".")[0]; if (m < 20) { console.error(`node ${process.versions.node}: this suite needs 20 or newer - on 19 the reporter dies mid-stream and it looks like a product failure`); process.exit(1); }'
# The same statement for Python: the tools use 3.10 syntax unless they carry the future import, and
# a version check that exists for one runtime and not the other is a claim about which one bites.
python3 -c 'import sys; sys.exit(0 if sys.version_info >= (3, 10) else (print(f"python {sys.version.split()[0]} - this suite needs 3.10+", file=sys.stderr) or 1))'
# **The count that is compared is the one the run produced.** A floor over *declarations* was written
# first and it measures the wrong thing twice over: cases generated by a loop expand at run time - 811
# `test(` in the files against 918 executed - so dropping an app or a fixture from one of those loops
# reduces what runs without changing a line of source, which is exactly the shrinkage the floor is
# named for. Consume the summary instead.
node --test --test-reporter=spec tests/*.test.mjs | tee "$NODEOUT"
# The spec reporter writes «ℹ tests N», the tap one «# tests N`»; match the number after the word
# rather than the decoration in front of it, so changing reporter does not silently stop the floor.
NODE_RAN=$(sed -nE 's/^[^0-9]*tests ([0-9]+)$/\1/p' "$NODEOUT" | tail -1)
# **A skipped case counts as run in that total**, which is the commonest way a case stops running and
# the one an exact number was supposed to notice: `test('x', { skip: … })` still appears in `tests N`.
#
# Printed, not refused, and the difference was learnt on GitHub. Refusing any skip is right about a
# *parked* case and wrong about an environment-gated one - `skipTest('no Chrome on this machine')` is
# how this suite says «the browser is what this asserts about and there is no browser», which is the
# honest answer and the one the runner needs. The rule that has no exception is «nobody parks a
# case», and that is a property of the source: `tests/tools_test.py` holds it, where a decorator is
# visible and a runtime skip carrying its reason is not a finding.
NODE_SKIPPED=$(sed -nE 's/^[^0-9]*skipped ([0-9]+)$/\1/p' "$NODEOUT" | tail -1)
[ "${NODE_SKIPPED:-0}" -eq 0 ] && echo "  no node case is skipped." \
  || echo "  ${NODE_SKIPPED} node case(s) skipped - they are inside the count above, so it cannot notice them."
# **`todo` is worse than `skip` and had no line at all.** A case marked todo still *runs*, is allowed
# to *fail*, is counted in `tests N`, and the runner exits 0 - so a broken product passes the whole
# battery in silence. Demonstrated: `statLinks` made to answer with the org's total and its case
# marked todo, everything green. Refused outright: there is no environment that makes a case todo.
NODE_TODO=$(sed -nE 's/^[^0-9]*todo ([0-9]+)$/\1/p' "$NODEOUT" | tail -1)
[ "${NODE_TODO:-0}" -eq 0 ] || {
  echo "  ${NODE_TODO} node case(s) are marked todo. A todo case runs, is allowed to fail, and the" >&2
  echo "  runner still exits 0 - which is a broken product with a green battery." >&2
  exit 1
}

[ "${NODE_RAN:-0}" -eq "$NODE_EXPECTED" ] || {
  if [ "${NODE_RAN:-0}" -lt "$NODE_EXPECTED" ]; then
    echo "  the node suite ran ${NODE_RAN:-no} case(s) and $NODE_EXPECTED were expected - cases stopped" >&2
    echo "  running, or were removed. A loop that stopped expanding loses cases without losing a line" >&2
    echo "  of source, which is what this number is here to notice." >&2
  else
    echo "  the node suite ran ${NODE_RAN} case(s), up from $NODE_EXPECTED - raise NODE_EXPECTED in the" >&2
    echo "  same commit as the cases that were added. This is the reminder, not a failure of the code." >&2
  fi
  exit 1
}

echo
echo "── unit: python ──"
# **The lines that say what happened, not the last three whatever they are.** `tail -3` was written
# when unittest's summary *was* the tail; work printed by the cases themselves - the store fields
# measuring their own ceilings - then arrived after it, and «Ran 391 tests / OK» fell off the bottom.
# A red run still fails the suite, so this was never a correctness hole; it is the one where a count
# nobody can see is a count nobody compares, which is how six cases that never ran said OK.
#
# So: the verdict and the count, then whatever the cases wanted to say, and nothing chosen by
# position. If unittest's summary ever stops being printed, `grep -c` finds nothing and this prints
# a line saying the report is missing rather than saying nothing at all.
python3 tests/tools_test.py > "$PYOUT" 2>&1 || { cat "$PYOUT"; exit 1; }
grep -E '^(Ran [0-9]+ tests?|OK|FAILED)' "$PYOUT" || echo "  (tests/tools_test.py printed no summary - it did not run to the end)"
PY_RAN=$(sed -nE 's/^Ran ([0-9]+) tests?.*/\1/p' "$PYOUT" | tail -1)
# Same on this side, and this is where the lesson arrived: two cases skip on GitHub's runner - no
# Chrome, a shallow clone - and refusing them turned a correct run red. Said, so the number above is
# read knowing what is inside it.
# Any «OK (…)» tail, not only a bare `skipped=N`: a run with an expected failure prints
# `OK (skipped=1, expected failures=1)` and the exact pattern matched nothing at all, so the script
# said «no python case is skipped» over a run that had skipped one.
PY_SKIPPED=$(sed -nE 's/^OK \(.*skipped=([0-9]+).*\)$/\1/p' "$PYOUT" | tail -1)
PY_XFAIL=$(sed -nE 's/^OK \(.*expected failures=([0-9]+).*\)$/\1/p' "$PYOUT" | tail -1)
[ "${PY_XFAIL:-0}" -eq 0 ] || {
  echo "  ${PY_XFAIL} python case(s) are expected failures - a case allowed to fail is a case not" >&2
  echo "  holding anything, and «Ran ${PY_RAN}» counts it as run." >&2
  exit 1
}
[ "${PY_SKIPPED:-0}" -eq 0 ] && echo "  no python case is skipped." \
  || echo "  ${PY_SKIPPED} python case(s) skipped - «Ran ${PY_RAN}» counts them; the reasons are in the file."

[ "${PY_RAN:-0}" -eq "$PY_EXPECTED" ] || {
  if [ "${PY_RAN:-0}" -lt "$PY_EXPECTED" ]; then
    echo "  the python suite ran ${PY_RAN:-no} case(s) and $PY_EXPECTED were expected - a file stopped" >&2
    echo "  being collected, or cases were removed." >&2
  else
    echo "  the python suite ran ${PY_RAN} case(s), up from $PY_EXPECTED - raise PY_EXPECTED in the same" >&2
    echo "  commit as the cases that were added." >&2
  fi
  exit 1
}
# The cases' own printing, which is what the rest of this block is for. `|| true` because a run whose
# output is only the summary is a legitimate run, and `set -o pipefail` would otherwise end it here.
grep -vE '^(Ran [0-9]+ tests?|OK|FAILED|-+$|\.*$|$)' "$PYOUT" | tail -5 || true

echo
echo "── driven in a browser ──"
# **The battery was green while this was red, and that is how two export defects reached the author's
# own screen in one day.** `srcBlock` was a `const` used above its declaration and this one was a
# backtick inside a comment inside a template literal: both parse, both die the moment the builder
# runs, and nothing that *reads* source has an opinion about either. The probe drives both panels
# against the sample workspace in a real Chrome and fails on any error the page logs - it caught the
# second one on the first run - but it lived in `prepare.sh`, which is the release routine. So the
# suite everybody runs said «green» about code that could not execute.
#
# One failure is enough to earn a check; this one had two. It is here now, and where Chrome is not
# installed it says so and passes, which is the only honest thing a probe can do on a machine it
# cannot drive.
#
# **And it runs here, third, rather than last.** `set -e` ends the run at the first red, so a check
# placed after the static ones is absent exactly when something is already wrong - which happened
# the same day it was added: `imgcheck` was red because the site pictures were being re-rendered,
# the run stopped there, and a third broken template literal shipped to the author's screen with
# the probe never executed. An ordering is a claim about which answer you want first, and the
# answer wanted first is «does the product still run».
python3 tools/probe.py

echo
echo "── checks ──"
python3 tools/twincheck.py | tail -1
python3 tools/asynccheck.py | tail -1
python3 tools/sitecheck.py | tail -1
python3 tools/aidatacheck.py | tail -1
python3 tools/samplecheck.py | tail -1
python3 tools/csscheck.py | tail -1
python3 tools/namecheck.py | tail -1
python3 tools/featurecheck.py | tail -1
python3 tools/htmlcheck.py | tail -1
python3 tools/callcheck.py | tail -1
python3 tools/imgcheck.py | tail -1
python3 tools/sitemap.py --check | tail -1
python3 tools/stamp.py --check | tail -1
python3 tools/notescheck.py | tail -1
python3 tools/langcheck.py | tail -1


echo
echo "── build ──"
# The archive is the point of the check, not of keeping: a local .zip of a version is the one
# artefact the release routine says must never be uploaded, so the suite does not leave one.
./build.sh crm >/dev/null && ./build.sh analytics >/dev/null && echo "both apps package"
rm -f dist/zoost-crm-*-store.zip dist/zoost-analytics-*-store.zip
